export {default as Adids} from './Adids.svg'
export {default as HM} from './H&M.svg'
export {default as NewBalance} from './NewBalance.svg'
export {default as Nick} from './Nick.svg'
export {default as NorthFace} from './NorthFace.svg'
export {default as Puma} from './Puma.svg'
export {default as Batch} from './Batch.svg'
export {default as Van} from './Van.svg'
export {default as Return} from './Return.svg'
export {default as Account} from './Account.svg'
export {default as ShopingBeg} from './ShopingBeg.svg'
export {default as Location} from './Location.svg'
export {default as Wallet} from './Wallet.svg'
export {default as Email} from './Email.svg'
export {default as Gift} from './Gift.svg'
export {default as FileUpload} from './FileUpload.svg'
export {default as QRcode} from './QRcode.svg'
export {default as Close} from './Close.svg'
export {default as NextArrow} from './NextArrow.svg'
export {default as BackArrow} from './BackArrow.svg'
export {default as Logo} from './Logo.svg'
export {default as Filter} from './Filter.svg'
export {default as SearchIcon} from './SearchIcon.svg'
export {default as CartIcon} from './CartIcon.svg'
export {default as Fire} from './Fire.svg'
export {default as DownArrow} from './DownArrow.svg'
export {default as Email1} from './Email1.svg'
export {default as Gift1} from './Gift1.svg'
export {default as Location2} from './Location2.svg'
export {default as Wallet1} from './Wallet1.svg'
export {default as Logout} from './Logout.svg'
export {default as Order} from './Order.svg'
export {default as OrderDitals} from './OrderDitals.svg'
export {default as Person} from './Person.svg'
export {default as Return1} from './Return1.svg'
export {default as Moon} from './Moon.svg'
export {default as Sun} from './Sun.svg'
export {default as Heart} from './Heart.svg'
export {default as Clock} from './Clock.svg'
export {default as Info} from './Info.svg'
export {default as Eye} from './Eye.svg'
export {default as Trending} from './Trending.svg'
export {default as Cardimg} from './Cardimg.svg'
export {default as Pen} from './Pen.svg'
export {default as Print} from './Print.svg'
export {default as Add} from './Add.svg'
export {default as Check} from './CheckMarkIcon.svg'
export {default as StarIcon} from './StarIcon.svg'
export {default as QualityIcon} from './QualityIcon.svg'
export {default as FitIcon} from './FitIcon.svg'
export {default as ComfortIcon} from './ComfortIcon.svg'
export {default as ThumbsUpIcon} from './ThumbsUpIcon.svg'
export {default as ThumbsDownIcon} from './ThumbsDownIcon.svg'
export {default as PayPalIcon} from './PayPalIcon.svg'
export {default as GiftImg} from './GiftImg.svg'
export {default as LogInIcon} from './LogInIcon.svg'






